добавлен дз 4-navigator и 5-laguages
Josef-adilson27/PurpleSchool_home_works pull request #1
Opened 2024-07-26 22:46 UTC by Josef-adilson27

2024-07-28 12:44 UTC, GitEsense approved these changes

2024-07-28 12:44 UTC, GitEsense commented on 5-languages/index.js
> +switch (lang) {
Можно было бы либо в момент объявления (принятия значения), либо на уровне switch реализовать приведение к нижнему регистру, чтобы сравнение имело "одинаковый" формат

```js
const lang = prompt().toLowerCase() // lang = 'RUS'.toLowerCase() = 'rus'
switch(lang.toLowerCase()){
 /* 
   ...
 */
}

2024-07-28 12:44 UTC, GitEsense commented on 6-driver/index.js
> +const CanHeDrive = (hasLicense && !isDrunk && age >= 18)?'can drive':'cannot drive'
У нас переменная гласит, что будет булево значение, следовательно хорошо бы вернуть булево, а уже потом на выводе сделать проверку, так же принято называть переменные в camelCase

```js
const canDrive = (hasLicense && !isDrunk && age >= 18)

console.log(`Водитель ${canDrive ? 'может' : 'не может'} управлять транспортным средством`);

2024-07-28 15:36 UTC, Josef-adilson27 commented on 6-driver/index.js
> +const CanHeDrive = (hasLicense && !isDrunk && age >= 18)?'can drive':'cannot drive'
Поспешил. Исправлено. На счет camelCase опечатался :)

2024-08-05 12:21 UTC, GitEsense requested changes
Всё хорошо, но крипто хорошо бы "доделать"

2024-08-05 12:21 UTC, GitEsense commented on 7-converter/index.js
> +
предложу вот такие вот варианты в качестве альтернативных вариантов решения:
**Вариант №1:**
```js
function converter(sum, currency, targetCurrency) {
    const USD = 90;
    const EUR = 100;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * USD;
                case 'EUR':
                    return (sum * USD) / EUR;
                default:
                    return null;
            }
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * EUR;
                case 'USD':
                    return (sum * EUR) / USD;
                default:
                    return null;
            }
        case 'RUB':
            switch (targetCurrency) {
                case 'USD':
                    return sum / USD;
                case 'EUR':
                    return sum / EUR;
                default:
                    return null;
            }
        default:
            return null;
    }
}
```

**Вариант №2:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = ['RUB', 'EUR', 'USD'];
    const USD = 91.33;
    const RUB = 1;
    const EUR = 112.33;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();
    const icon = getTargetCurrencyIcon(targetCurrency);

    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }
    if (!ALLOW_CURRENCY_LIST.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!ALLOW_CURRENCY_LIST.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    
    let value = null;

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, USD, RUB); break;
                case 'EUR': value = convertSum(sum, USD, EUR); break;
            }; break;
        case 'RUB':
            switch (targetCurrency) {
                case 'USD': value = convertSum(sum, RUB, USD); break;
                case 'EUR': value = convertSum(sum, RUB, EUR); break;
            }; break;
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, EUR, RUB); break;
                case 'USD': value = convertSum(sum, EUR, USD); break;
            }; break;
    }

    return messageTemplate(value, icon)
}
```

**Вариант №3:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = [['RUB', 1], ['EUR', 112.33], ['USD', 91.33]];
    const flatList = ALLOW_CURRENCY_LIST.flat();
    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    if (!flatList.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!flatList.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    const icon = getTargetCurrencyIcon(targetCurrency);
    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }

    const currentIndex = flatList.indexOf(currency) / 2;
    const targetIndex = flatList.indexOf(targetCurrency) / 2;
    const [, currentValue] = ALLOW_CURRENCY_LIST[currentIndex];
    const [, targetValue] = ALLOW_CURRENCY_LIST[targetIndex];
    const result = convertSum(sum, currentValue, targetValue)
    return messageTemplate(result, icon);
}
```

2024-08-05 12:21 UTC, GitEsense commented on 7-converter/index.js
> +    const  TargetingCurrency = targetingCurrency.toLowerCase().slice(0, 3)
не стоит называть переменные с "заглавной буквы" - это некорректно относительно camelCase

2024-08-05 12:21 UTC, GitEsense commented on 9-sort-loop/index.js
> +      arr[j+1] = t
Тут можно воспользоваться трюком обмена переменными
https://learn.javascript.ru/destructuring-assignment
```js
 if (arr[i] > arr[j]) {
     [arr[i], arr[j]] = [arr[j], [arr[i]]
}
```js
в примере ниже приведён пример

2024-08-05 12:21 UTC, GitEsense commented on 9-sort-loop/index.js
> +console.log(arr); //[-5, 0, 1, 10, 40]
Всё хорошо, только у нас идёт модификация исходного массива...
хорошо бы, если бы исходный массив не изменялся

Вот вариант реализации с направлением и без модификации исходного массива

```js
const numbers = Array.from({ length: 1000 }, () => {
    const max = 1000000;
    const min = 1000;
    const factor = Math.random() > 0.5 ? 1 : -1;
    const randomNumber = Math.ceil(Math.random() * (max - min)) + min;
    return randomNumber * factor;
});

function orderTemplate(firstNumber, secondNumber, desc) {
    if (!desc) {
        return firstNumber > secondNumber;
    }
    return firstNumber < secondNumber;
}

function sortArray(incomingArray, desc = false) {
    const array = [...incomingArray];
    for (let i = 0; i < array.length; i++) {
        for (let j = i; j < array.length; j++) {
            const isExchange = orderTemplate(array[i], array[j], desc);
            if (isExchange) {
                [array[i], array[j]] = [array[j], array[i]];
            }
        }
    }
    return array;
}

console.log(numbers);
console.log('Отсортированный по возрастанию массив:', sortArray(numbers));
console.log('Отсортированный по убыванию массив:', sortArray(numbers, true));

2024-08-05 12:21 UTC, GitEsense commented on crypto-8/index.js
> +  console.log(check("sswordpa", "qqqpassword")); //false
Функция check не должна по сути ничего делать со строкой, просто вернуть обратимость функции шифрования
и будет иметь вид что-то вроде
```js
function check(encypt, original) {
   if(!encrypt || !original) {
        return false
    }
    return crypto(encrypt) === original
}
```

А такая запись должна вернуть "true"
```js
const p = 'password'
const e = crypto(p)
const d = crypto(e);
console.log(p, e, d, p === d);  // сейчас вот так 'password', 'sswordpa', 'wordpass', false
console.log(p, e, d, p === d); // должно быть так 'password', 'sswordpa', password', true
```

2024-08-05 12:21 UTC, GitEsense commented on crypto-8/index.js
> +    return crypto(encrypted) === crypted ? true : false;
Вы шифруете "оригинальный" пароль и сравниваете с шифром, а у нас задача "обратимости", т.е. шифрованный пароль расшифровать и сравнить с оригинальным

2024-08-09 11:20 UTC, GitEsense requested changes
Оставил комментарий

2024-08-09 11:20 UTC, GitEsense commented on 8-crypto/index.js
> +};
Если реализовать функцию корректно, т.е. с обратимостью - то она будет работать не верно, т.к. Вы храните массив и делаете какие-то разные манипуляции.
Я ранее уже говорил, что функция check по сути проста как 5 копеек

1. Смотрим "не пустые ли" и "подходят ли по длине"  пароли
2. Возвращает результат строгого сравнения ORIGINAL и DECRYPTED PASSWORD 
```js
function checkPassword(ENCRYPTED_PASSWORD, ORIGINAL) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    const DECRYPTED_PASSWORD = crypt(ENCRYPTED_PASSWORD)
    return ORIGINAL === DECRYPTED_PASSWORD // true or false
}
```
Всё - тут больше ничего делать не надо - функция обращается просто "дешифрует" шифрованный пароль, т.е. работает "обратимость", т.е.

```js
const password = '12345678'
const encrypt = crypt(password); // '21438657';
const decrypt = crypt(encrypt); // '12345678';

console.log(password, encrypt, decrypt, password === decrypt) // '12345678' , '21438657', '12345678', true
```
Вот так должно отработать "корректно",
тогда мы уже сможем сделать просто запрос
```js
const result = check('12345678', '21438657'); // true
```
а уже сама функция "расшифрует" и вернёт результат, т.к. функция шифрования и дешифрования условно нам не известна, но мы знаем об обратимости и метода "check" может вообще не быть, например

2024-08-12 08:26 UTC, GitEsense approved these changes

2024-08-12 08:26 UTC, GitEsense commented on 8-crypto/index.js
> +console.log(check(password,'72345618')); //true
Вот теперь да, только перестановку делать как-то "динамически", оставляю пример для анализа:

```js
function crypt(password) {
    if (!password || !password.length) {
        return NaN;
    }
    const splitedArray = password.split('');
    if (splitedArray.length < 8) {
        return false;
    }

    const middleIndex = Math.floor(splitedArray.length / 2);
    const firstHalf = splitedArray.slice(0, middleIndex).reverse();
    const secondHalf = splitedArray.slice(middleIndex).reverse();
    const length = secondHalf.length;
    [secondHalf[1], secondHalf[length - 2]] = [secondHalf[length - 2], secondHalf[1]];

    const encryptedPassword = firstHalf.concat(secondHalf);
    return encryptedPassword.join('');
}

function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypt(encryptedPassword);
}

function getRandomNumber(min = 0, max = 86) {
    return Math.ceil(Math.random() * (max - min)) + min;
}

function getRandomPassword(length = 12) {
    const symbolArray = Array.from({ length: 87 }, (_, index) => String.fromCharCode(index + 33));
    console.log(symbolArray);
    const password = Array.from({ length }, () => symbolArray[getRandomNumber()]);
    return password.join('');
}

/*
    logging and test function with console
*/

const password = getRandomPassword();
const encrypted = crypt(password);

console.log('Пароль:', password);
console.log('Зашифрованный пароль:', encrypted);
console.log('Проверка пароля:', checkPassword(encrypted, password));

const password2 = getRandomPassword();
const encrypted2 = crypt(password2).substring(1);

console.log('Пароль:', password2);
console.log('Зашифрованный пароль:', encrypted2);
console.log('Проверка пароля:', checkPassword(encrypted2, getRandomPassword()));
```

2024-08-15 11:44 UTC, GitEsense requested changes
Необходимо доработать `11-date-array`

2024-08-15 11:44 UTC, GitEsense commented on 10-array-clean/index.js
> +    !callback(element) && filteredArray.push(element)
лучше так не делать, а сделать как "положено"
```js
if(!callback(element)){
    filteredArray.push(element);
}
```

2024-08-15 11:44 UTC, GitEsense commented on 11-date-array/index.js
> +console.log(res); //['21-12-2023', '31-03-2023', '31-11-2023', '09-12-2023']
Давайте за основу возьмём следующий массив:
```js
const arr = ['10/30/2020', '10-10-2021', '30-12-1987', '32-12-1987', '29-02-2023', '29-02-2024', '02/29/2023', '02/29/2024']
```
тогда при его валидации, элементы  с индексом : 0,  3, 4, 6, будут отброшены и останется результат
```js
[
    `30-10-2020`, 
    `10-10-2021`, 
    `30-12-1987`,
    `29-02-2024`
]
```

необходимо доработать следующую логику:
1. Валидация високосных дней (28 / 29 февраля)
2. Валидация коротких и длинных месяцев (30 и 31 день)
3. Если формат "RU" (`.` или `-` разделитель), то выводим с нужным разделителем
4. Если формат "EN" (`/` разделитель), то выводим с нужным разделителем, приведя в нужный формат (это Вы уже делаете, но как-то не полноценно, хотя и работает)

Посмотрите на предмет формата не по датам, а по разделителю, вспомните про `includes`

2024-08-15 11:44 UTC, GitEsense commented on 12-luna/index.js
> +  console.log(luna(num4));
Оставлю такой вариант
```js
function cardLunaValidate(card) {
    const cardNumber = card
        .replaceAll('-', '')
        .split('')
        .map((x) => Number(x));
    if (cardNumber.includes(NaN)) {
        return NaN;
    }
    const isEven = (cardNumber.length - 1) % 2 === 0;

    for (let i = Number(isEven); i < cardNumber.length; i = i + 2) {
        cardNumber[i] =
            cardNumber[i] * 2 > 9 ? cardNumber[i] * 2 - 9 : cardNumber[i] * 2;
    }
    const sum = cardNumber.reduce((total, el) => total + el);
    return sum % 10 === 0;
}
const card = '234s834503458353';
const card1 = '2342834503458353';
const card2 = '4561-2612-1234-5464';
const card3 = '4561-2612-1534-5464';

function resultTemplate(card) {
    const startString = `Карта с номером: ${card}`;
    const endString = `получила результат: ${cardLunaValidate(card)}`;
    return `${startString} ${endString}`;
}
console.log(resultTemplate(card));
console.log(resultTemplate(card1));
console.log(resultTemplate(card2));
console.log(resultTemplate(card3));
```

2024-08-22 08:18 UTC, GitEsense approved these changes
Вот теперь отлично!
Оставлю для "анализа"

```js
const length = 30;

function randomNumber(min = 1, max = 35) {
    return Math.floor(Math.random() * (max - min + 1) + min)
}
const inputDates = Array.from({ length }, () => {
    const factor = Math.random() > 0.5 ? '/' : '-';

    const dateArray = [
        factor === '-' ? randomNumber() : randomNumber(0, 15),
        factor === '-' ? randomNumber(0, 15) : randomNumber(),
        randomNumber(1900, 2050),
    ].map((x) => x.toString().padStart(2, '0'));
    return dateArray.join(factor);
}).concat(Array.from({ length: 10 }, () => [randomNumber(28, 32), '02', randomNumber(1900, 2050)].join('-')));

function getDates(array, fn) {
    return array.map(stringToArray).filter(fn).sort(sortDatePattern).map(formatDate);
}

function formatDate(array) {
    return array.map(String).map((x, i) => (i === 2 ? x.padStart(4, '0') : x.padStart(2, '0'))).join('-');
}

function sortDatePattern(a, b) {
    let day, month, year;

    [day, month, year] = a;
    const dt1 = new Date(year, month - 1, day).getTime();

    [day, month, year] = b;
    const dt2 = new Date(year, month - 1, day).getTime();

    return dt1 - dt2;
}

function stringToArray(str) {
    let day, month, year;
    if (str.includes('/')) {
        [month, day, year] = str.split('/').map(x => parseInt(x));
    } else if (str.includes('-')) {
        [day, month, year] = str.split('-').map(x => parseInt(x));
    }

    if (!year || isNaN(day) || isNaN(month) || isNaN(year)) {
        return null;
    }
    return [day, month, year];
}

function checkCorrectDate(array) {
    if (array === null) {
        return false;
    }

    const [day, month, year] = array

    const LONG_MONTH_ARRAY = [1, 3, 5, 7, 8, 10, 12];

    const isLeapYear = (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;

    // check month
    if (month < 1 || month > 12 || year <= 0) {
        return false;
    }

    // check day
    if (day < 1 || day > 31) {
        return false;
    }

    if (day === 31 && !LONG_MONTH_ARRAY.includes(month)) {
        return false;
    }

    // check February for correct day and leap year
    if (month === 2 && ((day === 29 && !isLeapYear) || day > 29)) {
        return false;
    }
    return true;
}

const res = getDates(inputDates, checkCorrectDate);
console.log(inputDates);
console.log(res);
```

2024-08-29 01:47 UTC, merged